baseurl = "https://loehx.github.io/"
title = "Alexander Löhn"
theme = "coder-portfolio"
languagecode = "en"
defaultcontentlanguage = "en"

publishDir = "public"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Alexander Löhn"
    info = "Team-Lead<br>Developer<br>Trainer"
    description = "Alexander Löhn's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    hideCredits = false
    hideCopyright = false

    custom_css = ["css/main.css", "css/project.css", "css/projects.css"]

    itemscentered = true
    rtl = false
    snsShare = true
    thumbnail = "images/tn.png"
    langseparator = "|"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/loehx/"
[[params.social]]
    name = "XING"
    weight = 2
    url = "https://www.xing.com/profile/Alexander_Loehn2"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/alexander-loehn/"

# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "about"
